name: Minify CSS

on:
  push:
    branches: [ main ]
    paths:
      - 'classless.css'

jobs:
  minify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install clean-css-cli -g

      - name: Minify CSS
        run: |
          cleancss -o classless.min.css classless.css

      - name: Commit minified file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add classless.min.css
          git diff --quiet && git diff --staged --quiet || git commit -m "Minify CSS"
          git push
